config/routes.rb
ResearchMatch::Application.routes.draw do

  resources :pictures

  get '/' => 'home#index', :as => :home

  get '/dashboard' => 'dashboard#index', :as => :dashboard

  scope '/jobs', :as => :jobs do
    get '/search' => 'jobs#index', :as => :search
  end

  resources :jobs do
    member do
      get 'activate'
      get 'delete'
      get 'resend_activation_email'
      get 'watch'
      get 'unwatch'
    end
  end

  get '/team', :to => 'team#team'

  get '/intro', :to => 'intro#intro'

  get '/contact' => 'contact#contact', :as => :contact_us
  post '/contact/send_email', :as => :feedback_email_link

  get '/privacy' => 'privacy#index', :as => :privacy

  get '/statistics'      => 'statistics#index', :as => :statistics

  scope :applics do
    get  '/jobs/:job_id/apply' => 'applics#new', :as => :new_job_applic
    post '/jobs/:job_id/apply' => 'applics#create', :as => :create_job_applic
    get  '/jobs/:job_id/applications' => 'applics#index', :as => :list_jobs_applics
    get  '/applications/:id' => 'applics#show', :as => :applic
    get  '/applications/:id/withdraw' => 'applics#destroy', :as => :destroy_applic
    get  '/applications/:id/delete' => 'applics#delete', :as => :delete_applic
    post '/applications/:applic_id' => 'applics#accept'
    post '/applications/:applic_id/unaccept' => 'applics#unaccept'
  end # applics

  resources :documents

  get '/logout' => 'user_sessions#destroy'
  get '/login'  => redirect('/auth/cas')
  get '/login_with_google' => redirect('/auth/google_oauth2'), :as => :google_login
  get '/auth/:provider/callback' => 'user_sessions#new'

  resources :users
  get  '/profile'   => 'users#profile', :as => :profile

  resources :faculties, only: :show

  resources :orgs, param: :abbr
  post '/orgs/:abbr/curate' => 'orgs#curate', :as => :orgs_curate
  post '/orgs/:abbr/uncurate' => 'orgs#uncurate', :as => :orgs_uncurate

  get '/categories/json' => 'categories#json', :as => :categories_json, :defaults => {format: 'json'}
  get '/courses/json' => 'courses#json', :as => :courses_json, :defaults => {format: 'json'}
  get '/proglangs/json' => 'proglangs#json', :as => :proglangs_json, :defaults => {format: 'json'}

  get '/admin' => 'admin#index', :as => :admin
  post '/admin/upload' => 'admin#upload', :as => :admin_upload
  post '/admin/send_email' => 'admin#send_email', :as => :admin_send_email

  get '/rails/mailers' => "rails/mailers#index"
  get '/rails/mailers/*path' => "rails/mailers#preview"

  root :to => 'home#index'

  get '/test_error(/:code)' => 'application#test_exception_notification'

  get "*any", via: :all, to: "errors#not_found"

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  user_id    :integer
#  job_id     :integer
#  created_at :datetime
#  updated_at :datetime
#

class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :job
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/edit.html.erb
<h1>Editing picture</h1>

<% form_for(@picture) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table>
  <tr>
    <th>Url</th>
    <th>User</th>
    <th>Job</th>
  </tr>

<% @pictures.each do |picture| %>
  <tr>
    <td><%=h picture.url %></td>
    <td><%=h picture.user %></td>
    <td><%=h picture.job %></td>
    <td><%= link_to 'Show', picture %></td>
    <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
    <td><%= link_to 'Destroy', picture, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<% form_for(@picture) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </p>
  <p>
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </p>
  <p>
    <%= f.label :job %><br />
    <%= f.text_field :job %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p>
  <b>Url:</b>
  <%=h @picture.url %>
</p>

<p>
  <b>User:</b>
  <%=h @picture.user %>
</p>

<p>
  <b>Job:</b>
  <%=h @picture.job %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>